
---
baseurl: "https://mrkeelan.github.io/"
languageCode: "en-us"
title: "Matthew Keelan Blog"
theme: "hyde-x"
metaDataFormat: "yaml"
taxonomies:
  category: "categories"
author:
  name: "Matthew Keelan"
params:
  tagline: "A Blog about nothing"
  #googleAnalytics: "UA-60318539-2"
  #gravatarHash: "15cb4683f9aa1f015998d230b61b0ef7"
  copyright: "Matthew Keelan."
  twitter: "https://twitter.com/mrkeelan"
  github: "https://github.com/mrkeelan"
